### ISSUE TITLE
Style of String Quoting Matters

### ISSUE THREAD

**Issue by JavascriptFTW** [Khan/structuredjs#22] opened 2015-11-18 00:27 UTC
This issue was pointed out in an [issue](https://github.com/Khan/live-editor/issues/433) on the Khan/live-editor repository, namely that structuredjs considers whether strings are quoted using double or single quotes when testing for a match.

Example:

```
var heading = _ + "px";
```

Will not match:

```
var heading = amount + 'px';
```

While this behavior may be desirable in certain cases in most cases it would end up confusing the student more than it helps.

**Comment by mr-martian** [comment] 2015-11-18 00:31
The issue is probably with the ```raw``` parameter of type ```Literal``` nodes. This would probably be fixed by adding a special case for comparing literals.

**Comment by mr-martian** [comment] 2015-11-18 00:54
case "Literal":
          if (typeof tree.value === "string" && tree.raw[0] === "'") {
            tree.raw = '"' + tree.raw.slice(1,-1) + '"';
          }
in ```standardizetree();``` appears to do it.
Though I tested this on my local copy, so you may have to replace ```tree``` with ```r```.

**Comment by kevinbarabash** [comment] 2016-04-07 15:23
In the future it would be nice if `exactMatchNode` took into account the node type when doing the comparison.  Then we could just compare the `.value` of the nodes against each other instead of having to rewrite the `raw` property.  I'm not sure of all of the implications of this change yet.

**Closed** 2016-04-30 23:19 UTC
Labels: enhancement
